/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signup` | `/signup`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/welcome` | `/welcome`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/LibraryScreen` | `/LibraryScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/NowPlaying` | `/NowPlaying`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Search` | `/Search`; params?: Router.UnknownInputParams; } | { pathname: `/api-config/api`; params?: Router.UnknownInputParams; } | { pathname: `/api-config/spotify`; params?: Router.UnknownInputParams; } | { pathname: `/components/AddPlaylistForm`; params?: Router.UnknownInputParams; } | { pathname: `/components/PlaylistView`; params?: Router.UnknownInputParams; } | { pathname: `/context/auth`; params?: Router.UnknownInputParams; } | { pathname: `/context/musicContext`; params?: Router.UnknownInputParams; } | { pathname: `/spotify_service/spotify`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/signup` | `/signup`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/welcome` | `/welcome`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/LibraryScreen` | `/LibraryScreen`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/NowPlaying` | `/NowPlaying`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/Search` | `/Search`; params?: Router.UnknownOutputParams; } | { pathname: `/api-config/api`; params?: Router.UnknownOutputParams; } | { pathname: `/api-config/spotify`; params?: Router.UnknownOutputParams; } | { pathname: `/components/AddPlaylistForm`; params?: Router.UnknownOutputParams; } | { pathname: `/components/PlaylistView`; params?: Router.UnknownOutputParams; } | { pathname: `/context/auth`; params?: Router.UnknownOutputParams; } | { pathname: `/context/musicContext`; params?: Router.UnknownOutputParams; } | { pathname: `/spotify_service/spotify`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/signup${`?${string}` | `#${string}` | ''}` | `/signup${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/welcome${`?${string}` | `#${string}` | ''}` | `/welcome${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/home${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/LibraryScreen${`?${string}` | `#${string}` | ''}` | `/LibraryScreen${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/NowPlaying${`?${string}` | `#${string}` | ''}` | `/NowPlaying${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/Search${`?${string}` | `#${string}` | ''}` | `/Search${`?${string}` | `#${string}` | ''}` | `/api-config/api${`?${string}` | `#${string}` | ''}` | `/api-config/spotify${`?${string}` | `#${string}` | ''}` | `/components/AddPlaylistForm${`?${string}` | `#${string}` | ''}` | `/components/PlaylistView${`?${string}` | `#${string}` | ''}` | `/context/auth${`?${string}` | `#${string}` | ''}` | `/context/musicContext${`?${string}` | `#${string}` | ''}` | `/spotify_service/spotify${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signup` | `/signup`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/welcome` | `/welcome`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/LibraryScreen` | `/LibraryScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/NowPlaying` | `/NowPlaying`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Search` | `/Search`; params?: Router.UnknownInputParams; } | { pathname: `/api-config/api`; params?: Router.UnknownInputParams; } | { pathname: `/api-config/spotify`; params?: Router.UnknownInputParams; } | { pathname: `/components/AddPlaylistForm`; params?: Router.UnknownInputParams; } | { pathname: `/components/PlaylistView`; params?: Router.UnknownInputParams; } | { pathname: `/context/auth`; params?: Router.UnknownInputParams; } | { pathname: `/context/musicContext`; params?: Router.UnknownInputParams; } | { pathname: `/spotify_service/spotify`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
